FROM php:7.3.6-fpm-alpine3.9

run apk add --no-cache bash mysql-client openssl nodejs npm
RUN docker-php-ext-install pdo pdo_mysql


WORKDIR /var/www
RUN rm -rf /var/www/html
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


COPY . /var/www

RUN composer install && php artisan config:cache && chmod -R 777 storage

RUN npm install
RUN chown -R www-data:www-data /var/www

RUN ln -s public html

expose 9000
ENTRYPOINT ["php-fpm"]
